[project]
name = "polymind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ankith Mall", email = "ankithmall1729@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.27.0",
    "llama-cpp-python>=0.3.35",
    "psutil>=7.2.2",
    "pyaml>=26.7.0",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "typer>=0.27.1",
]

[project.scripts]
polymind = "polymind.client.cli.app:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
